# Multi-stage production builds keep images small and cost-effective to store in ECR
FROM node:20-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine
WORKDIR /usr/src/app
USER node
COPY --chown=node:node --from=builder /usr/src/app/node_modules ./node_modules
COPY --chown=node:node ./src ./src
COPY --chown=node:node package.json ./

EXPOSE 80
ENV NODE_ENV=production
CMD [ "npm", "start" ]
